Suppress -Wparentheses diagnostics for consecutive comparisons
These errors appear after upgrading to clang-r547379:

system/tools/hidl/test/hidl_test/static_test.cpp:164:74: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Werror,-Wparentheses]
  164 | static_assert(IExpression::Precedence::boolExpr1 == (!((3 != 4 || (2 < 3 <= 3 > 4)) >= 0)), "");
      |                                                                          ^
system/tools/hidl/test/hidl_test/static_test.cpp:164:79: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Werror,-Wparentheses]
  164 | static_assert(IExpression::Precedence::boolExpr1 == (!((3 != 4 || (2 < 3 <= 3 > 4)) >= 0)), "");
      |                                                                               ^
system/tools/hidl/test/hidl_test/static_test.cpp:165:83: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Werror,-Wparentheses]
  165 | static_assert(IExpression::Precedence::boolExpr == (1 == 7 && !((3 != 4 || (2 < 3 <= 3 > 4)) >= 0)),
      |                                                                                   ^
system/tools/hidl/test/hidl_test/static_test.cpp:165:88: error: comparisons like 'X<=Y<=Z' don't have their mathematical meaning [-Werror,-Wparentheses]
  165 | static_assert(IExpression::Precedence::boolExpr == (1 == 7 && !((3 != 4 || (2 < 3 <= 3 > 4)) >= 0)),
      |                                                                                        ^

These new comparison diagnostics don't have a sub-group, so specify
-Wparentheses, which also suppresses the logical-op and bitwise-op
diagnostics.

Bug: http://b/379133546
Test: m hidl_test_client
Change-Id: I2f15e3e8a1213ad4b34a81a41ed8a06dee9bc1d7